config/routes.rb
MFCPortal::Application.routes.draw do

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :activities
  resources :categories do
    resources :events
  end

  resources :events do
    resources :expenses
    collection do
      get "dashboard"
      get "welcome"
      get "gallery"
      get "contact_us"
      get "other_activity"
      get "event_activity_list"
    end
  end

  root :to => "events#dashboard"

end

app/views/shared/_admin.html.erb
<% if user_signed_in? %>
  <div class="well span2" style="min-height: 500px;width: 215px;"><font size="2px">
  
  <ul class="nav nav-pills nav-stacked" style="text-align: left;">
    <li class="active">
    <%= link_to 'Home', welcome_events_path %>
    </li>
    
    <li><%= link_to 'Events', events_path %></li>
    
    <% if current_user.role.downcase == 'admin'%>
    <li><%= link_to 'View Event Activites', event_activity_list_events_path %></li>
    <%end%>

    <% if current_user.role.downcase == 'admin'%>
    <li><%= link_to 'Manage Event Categories', categories_path %></li>
    <%end%>
  </ul>

  </font></div>
<%end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-fixed-top"style="height:30px">
  <div class="navbar-inner" style="height:30px;padding-top: 10px;">
    
    <div style = "margin-left :10px;">
      <b style="font-size:15px;color:white;margin-left:30px"><%= link_to "Home", welcome_events_path%> &nbsp; &nbsp;<%= link_to "Dashboard", dashboard_events_path%></b></font>
    </div>

    <div class="nav-collapse pull-right">
      <ul class="nav" style="margin:-30px 10px 0 0;">
        <li class="active"></li>
        <li class="dropdown">
          <a href="#"
            class="dropdown-toggle";
            data-toggle="dropdown";>
              <b><font color= "white" size="2px">
                Welcome, <%= current_user.email %>
              </font></b>
              <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
            <li class="divider"></li>
            <li> <%= link_to "Sign out", destroy_user_session_path , :method => :delete%> </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>    
</div>

<br>
<br> 
<br>