config/routes.rb
MFCPortal::Application.routes.draw do

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :activities
  resources :categories do
    resources :events
  end

  resources :events do
    resources :expenses
    collection do
      get "dashboard"
      get "welcome"
      get "gallery"
      get "contact_us"
      get "other_activity"
      get "event_activity_list"
    end
  end

  root :to => "events#dashboard"

end

app/models/event.rb
class Event < ActiveRecord::Base
  #relationship wuth activities
  has_many :activities, :dependent => :destroy
  #relationship with expenses
  has_many :expenses
  attr_accessible :title, :description, :category_id, :start_date, :end_date, :category_id, :start_time, :end_time
   
  validates :title, :description, :category_id, :start_date, :end_date, :presence => true
  validates_length_of :title, :within => 6..30, :too_long => "Pick a shorter Title", :too_short => "Pick a longer Title"
  belongs_to :category
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  #load_and_authorize_resource
  skip_filter :authenticate_user!, :only => [:dashboard, :gallery, :contact_us]

  def welcome
  end
    
  def gallery
  end

  def contact_us
  end

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
    @activities = Activity.all
    #@categories = Category.all
  end

  def dashboard
    @events = Event.all
    @activities = Activity.all
    @categories = Category.all
  end

    
  def create
    @activities = Activity.all
    @categories = Category.all
    @event = Event.new (params[:event])
   
    category = Category.create_new_category(params[:event][:category_id], params[:new_category_name], params[:new_category_description], current_user)
    @event.category_id = category
    @event.created_by = current_user.id
    @event.updated_by = current_user.id
    @event.save
    # activities = Activity.create_new_activities(params[:new_activity_title], params[:new_activity_description], current_user )

    if !params[:new_activity_title].nil?
      @activity = Activity.new(:title => params[:new_activity_title], :description => params[:new_activity_description], :created_by => current_user.id, :event_id => @event.id)
      @activity.save
    else  
    end

    # EventsActivity.add_event_activities(@event, activities)     
    if @event.save
      flash[:notice] = "Successfully created a new Event."
      redirect_to events_path
    else
      flash[:notice] = @event.errors.full_messages.join(", ")
      render :action => :new
    end

  end


  def show
    @event = Event.find(params[:id])
    # @eventsActivities = EventsActivity.where("event_id = #{@event.id}")
    @expenses = Expense.where("event_id = #{@event.id}")
  end


  def destroy
    @event = Event.find(params[:id])
    # EventsActivity.destroy_all("event_id = #{@event.id}")
    Expense.destroy_all("event_id = #{@event.id}")
        
    @event.destroy
    if @event.destroy
      flash[:notice] = "Successfully deleted Event."
      redirect_to events_url
    else
      flash[:notice] = "Event Could Not Be deleted."
      redirect_to events_url
    end
        
  end

    
  def edit
    @event = Event.find(params[:id])
    # @activities = Activity.all
    @categories = Category.all
  end


  def update
    @event = Event.find(params[:id])

    # activities = Activity.create_new_activities(params[:activities], params[:new_activity_title], params[:new_activity_description], current_user)
    # EventsActivity.update_event_activities(@event, activities)

    category = Category.create_new_category(params[:event][:category_id], params[:new_category_name], params[:new_category_description], current_user)
    params[:event][:category_id] = category

    if @event.update_attributes(params[:event])
      flash[:notice] = "Successfully Updated Event."
      redirect_to event_path(params[:id])
    else
      flash[:notice] = @event.errors.full_messages.join(", ")
      render :action => :edit
    end

  end

  def event_activity_list
    @events = Event.all
  end

  def other_activity
    respond_to do |format|
      format.js {}
    end
  end
    
end

app/helpers/event_helper.rb
module EventHelper


end

app/views/events/_form.html.erb
<%= form_for (@event), :html => {:id => "event_form"} do |f| %>
  <table>
    <tr>
      <td>
        <div>
            <b><font size="3px">Title</font></b><br/>
            <%= f.text_field :title %>
        </div>
      </td>

      <td>  
        <div id='em_title' class = "errors">

        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div>
          <b><font size="3px">Select Event's Category:</font></b><br/>
          <%=collection_select(:event, :category_id, Category.all, :id, :name) %>
        </div></br>

        <div>
          Want to add a new Category ? <%= check_box_tag 'new_category_check' %>
        </div>

        <div id ="add_new_category" style="display: none;">
          <div class="well span3" style ="margin-right: 100px">
            <div><b><font size="3px">New Category </font></b><br/>
              <%= text_field_tag :new_category_name %></div><br/>

            <div><b><font size="3px">New Category Description</font></b><br/>
              <%= text_field_tag :new_category_description %></div><br/>
          </div>
        </div>
      </td>

      <td>

        <div id='em_category' class = "errors">
        </div> 
      </td>  

    </tr>

    <tr>
      <td>
        <div>
          <b><font size="3px">Description</font></b><br/>
          <%= f.text_area :description , :rows => 5 %>
        </div>
      </td>

      <td>  
        <div id='em_description' class = "errors" >

        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div>
           <%= link_to "Add Activity", other_activity_events_path, {:remote => true, :id => "other_activity", :method => :get} %> <div id = "new_activity"></div>
        </div>
      </td>

      <td> 
        <div id='em_activities' class = "errors"> </div> 
      </td>  
    </tr>

    <tr>
      <td>
        <div style= "height:20px">
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div>
          <b><font size="3px">Start Date </font></b><br/>
          <%= f.text_field :start_date, :readonly => true%>
        </div>
      </td>

      <td>  
        <div id='em_start_date' class = "errors">

        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div>
          <b><font size="3px">End Date </font></b><br/>
          <%= f.text_field :end_date, :readonly => true %>
        </div>
      </td>

      <td>  
        <div id='em_end_date' class = "errors">

        </div>
      </td>
    </tr>

    <tr>
      <span class="timeEntry_control" style="display: inline-block; background: url("img/spinnerDefault.png") no-repeat scroll 0px 0px transparent; width: 20px; height: 20px;" title="Next field"></span>
    </tr>

    <tr>
      <td>
        <div>
          <b><font size="3px">Start Time </font></b><br/>
          <%= f.text_field :start_time%>
        </div>
      </td>

      <td>  
        <div id='em_start_time' class = "errors">

        </div>
      </td>
    </tr>


    <tr>
      <td>
        <div>
          <b><font size="3px">End Time </font></b><br/>
          <%= f.text_field :end_time%>
        </div>
      </td>

      <td>  
        <div id='em_end_time' class = "errors">

        </div>
      </td>
    </tr>







    <tr>
      <div style="height: 20px">
      </div>
    </tr>

    <tr>
      <td>
        <div id = "event_form_submit" class="actions" ><%= f.submit%>
        </div>
      </td>
    </tr>
  </table>
<%end%>

app/views/events/_other_activity.html.erb
<div style= "height:20px">
</div>
<div class="well span5" style ="margin-right: 400px"> 
	<table>
		<tr>
			<td align ="center"><b><font size="3px">Activity Title</font></b>&nbsp&nbsp</td>
			<td align ="center"><b><font size="3px">Activity Description</font></b></td>
		</tr>

		<tr>	
			<td align ="center"><%= text_field_tag :new_activity_title %>&nbsp&nbsp</td>
		
			<td align ="center"><%= text_field_tag :new_activity_description %></td>
		</tr>
 	</table>
</div>

app/views/events/contact_us.html.erb
<div id="wrapper-dash">
  <div id="header-wrapper-dash">
    <div id="header-dash">
      <div id="menu1">
        <ul>
          <li class="current_page_item"><%=link_to "Gallery", gallery_events_path%></li>
        </ul>
      </div>
      <div id="logo">
        <h1 style="color:white">M.F.C</h1>
        <p>Firm Fun Committee</p>
      </div>
      <div id="menu2">
        <ul>
          <li><%=link_to "Contact Us", contact_us_events_path%></li>
        </ul>
      </div>
    </div>
    <!-- end #header -->
  </div>
  <div id="welcome">
    <h2 class="title"><a href="#">Welcome to MFC </a></h2>
    <div class="entry">
      <p>This is a fun side of <strong>Firm ODC</strong>. A committee which deals with all the fun activities to be organized within the ODC. The floor meetings of every month is an initiative taken by MFC to update the associates of the current month's activities.</p>
    </div>
  </div>

  <div id="welcome">

    <div id="page-dash">
      <h3>People to reach to :</h3>
      <p style ="color: white;">
        Mihir Bhatt<br/>
        Mustufa<br/>
        Atul Patel<br/>
        Nitish Nalan<br/>
        Prastuti<br/>
        Vikram Singh<br/>
        Kriti<br/>
        Ekta Verma<br/>
        Sarika<br/>
        Sourashish Misra<br/>
      </p>
    </div>
<%= link_to 'Back', dashboard_events_path %>
  </div>


</div>
<div id="footer-dash">
  <p>M.F.C</p>
</div>

app/views/events/dashboard.html.erb
<div id="wrapper-dash">
  
  <div id="header-wrapper-dash">
    <div id="header-dash">
      <div id="menu1">
        <ul>
          <li class="current_page_item"><%=link_to "Gallery", gallery_events_path%></li>
        </ul>
      </div>
      <div id="logo">
        <h1 style="color:white"><%=link_to "M.F.C", dashboard_events_path%></h1>
        <p>Firm Fun Committee</p>
      </div>
      <div id="menu2">
        <ul>
          <li><%=link_to "Contact Us", contact_us_events_path%></li>
        </ul>
      </div>
    </div>
  </div>

  
<div id="welcome">
  <%if @events.blank?%>
    
    <h2><h2 style="line-height: 100px;">No Events</h2></h2>

  <%else%>
    <% @events = Event.find(:all, :order => 'start_date').reverse%>
    <% @events.each do |event|%>
      <div>
        <font size="5px"><b><%= event.title.titleize%></b></font> &nbsp <font size ="3px">(<%=event.start_date.to_date.strftime('%d %b %Y')%>)</font>
      </div>
        
      <div class="entry" style="padding-bottom :10px; padding-top :10px">
        <p><%=event.description%></p>    
      </div>

      <div class="entry" style="padding-bottom :60px; padding-top :10px">
        <p>Activities Happened:</p>    
      </div>

      <div id="page-dash">
          <%i = 0%>
          <%if event.activities.count > 0%>
            <% event.activities.each do |eA|%>
              <%if i%3 == 0 %>
                <div id="column1">
                  <h4><%= eA.title.titleize %></h4>
                  <p style="color:white;"><%= eA.description%></p>
                </div>
              <%end%>
            
              <%if i%3 == 1 %>
                <div id="column2">
                  <h4><%= eA.title.titleize %></h4>
                  <p style="color:white;"><%= eA.description%></p>
                </div>
              <%end%>
            
              <%if i%3 == 2%>
                <div id="column3">
                  <h4> <%= eA.title.titleize %></h4>
                  <p style="color:white;"><%= eA.description%></p>
                </div>
              <%end%>

              <%i = i+1 %>
            <%end%>
          <%else%>
            <div id="column1" style="float:left;">
              <h2>No Activities Added</h2>
            </div>
          <%end%>
      </div>

    <%end%>
  <%end%>
</div>

    
</div>
<div id="footer-dash">
  <p>M.F.C</p>
</div>

app/views/events/edit.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px"> 
<div>
  <h2> Edit Event </h2>
  <br/>
  <%=render 'form' %>
<%= link_to 'Manage Expenses', event_expenses_path(@event) %> |
<%= link_to 'View', event_path(@event) %> |
<%= link_to 'Back', events_path %>

</div>
</div>

app/views/events/event_activity_list.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px"> 
<%if @events.blank? %>
<div>
</div>
<%else%>
<div style="overflow:auto;">
    <table border ="1px" id="activity_list_table" align = "center" >
      <thead>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><b>Event ID</b></td>
          <td style=" min-width: 20px "><b>Event Title </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; max-width: 250px "><b>Activities </b></td>
        </tr>
      </thead>

      <%@events.each do |event|%>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><%= event.id%></td>
          <td style=" min-width: 20px "><%= event.title%></td>

          <td style=" padding-right: 5px; padding-left: 5px; max-width: 250px"><% event.activities.each do |eA|%><%= eA.title %>,<%end%></td>
   
        </tr>
      <%end%>
    </table>
  </div>
  <%end%>
  <div style ="margin-top :10px;  margin-left :90px">
  <%= link_to 'Back', events_path %>
</div>
  </div>

app/views/events/gallery.html.erb
<div id="wrapper-dash">
  <div id="header-wrapper-dash">
    <div id="header-dash">
      <div id="menu1">
        <ul>
          <li class="current_page_item"><%=link_to "Gallery", gallery_events_path%></li>
        </ul>
      </div>
      <div id="logo">
        <h1 style="color:white">M.F.C</h1>
        <p>Firm Fun Committee</p>
      </div>
      <div id="menu2">
        <ul>
          <li><%=link_to "Contact Us", contact_us_events_path%></li>
        </ul>
      </div>
    </div>
    <!-- end #header -->
  </div>

  <div id="welcome">
    <h2 class="title"><a href="#">Welcome to MFC </a></h2>
    <div class="entry">
      <p>This is a fun side of <strong>Firm ODC</strong>. A committee which deals with all the fun activities to be organized within the ODC. The floor meetings of every month is an initiative taken by MFC to update the associates of the current month's activities.</p>
    </div>
  </div>

  <div id="welcome">
  <div id="page-dash">
<h2 style ="color: white;">Coming Soon</h2>
<%= link_to 'Back', dashboard_events_path %>

</div>
</div>
</div>

app/views/events/index.html.erb
<%= render 'shared/admin' %>
<div class= "well span5" style = "min-height:500px; margin-left:50px "> 
<%if @events.blank? %>
<div>
</div>
<%else%>
<div style="overflow:auto;">
    <table border ="1px" id="event_list_table" align = "center">
      <thead>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><b>Event ID</b></td>
          <td style=" min-width: 20px "><b>Title </b></td>
          <td style=" min-width: 20px "><b>Expenses</b></td>

          <td style=" min-width: 20px "><b> Delete </b></td>
        </tr>
      </thead>

      <%@events.each do |event|%>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><%= event.id%></td>
          <td style=" min-width: 20px "><%= link_to "#{event.title}", event_path(event) %></td>
          <td style=" min-width: 20px "><%= link_to "Expenses", event_expenses_path(event) %></td>

          <td style=" min-width: 20px "><%= link_to (image_tag ("delete.png")), event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
       <%end%>
    </table>
</div>
<%end%>  
<div style = "margin-top: 20px; margin-left: 160px">
<%= link_to 'Create New Event', new_event_path %><br/>
</div>
</div>    

app/views/events/new.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px"> 
 <div>
   <h2> Add New Event </h2>
   <br/>
   <%=render 'form' %>
   <div class="actions"> <%= link_to 'Cancel', events_path %> </div>
 </div>
</div>

app/views/events/other_activity.js.erb
$('#new_activity').html('<%= escape_javascript render("other_activity") %>');

app/views/events/show.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px"> 
<div>
  <h2> <%= @event.title.capitalize %> </h2>
</div>
  <br/>
  <div>
    <div><b><font size="2px">Type Of Event:</font></b>
      <%  @category = Category.find(@event.category_id)%>
      <%=  @category.name%>
    </div><br/>  

    <div><b><font size="2px">Description:</font></b>
      <%= @event.description.capitalize %></div><br/>

    <div><b><font size="2px">Activites:</font></b><br/>
      <% @event.activities.each do |eA|%>
       <%= eA.title %><br/>
      <%end%>
    </div><br/>

    <div><b><font size="2px">Expenses:</font></b><br/>
      <% @event.expenses.each do |eE|%>
       <%= eE.amount %><br/>
      <%end%>  
    </div><br/>

    <div><b><font size="2px">Start Date: </font></b>
      <%= @event.start_date.to_date %></div><br>

    <div><b><font size="2px">End Date: </font></b>
      <%= @event.end_date.to_date %></div><br/>
    
    <div style="height: 20px">
    </div>
</div>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>
</div>

app/views/events/welcome.html.erb
<%= render 'shared/admin' %>
<div class ="pull-right" style="min-height: 200px; width: 750px; margin-right:200px">
  <div class="flexslider">
      <ul class="slides">
        <li>
           <img src="/assets/2.PNG" />     
         </li>

        <li>   
           <img src="/assets/2.PNG" /> 
        </li>   

       <li>       
          <img src="/assets/2.PNG" />  
       </li>   

      <li>    
         <img src="/assets/2.PNG" />   
      </li>   
    </ul> 
  </div>  
</div>

<div class ="well span7 pull-right" style="height: 125px ;margin-right:225px">
<h2 align ="center"><font face= "serifa" color="0099FF"><i>Welcome   To    MFC    Portal</i></font></h2>
<p><font face= "serifa" color="gray"><i> Hi! This is a portal to capture all the events happening in and around Firm ODC. Check out all the latest and upcoming events in the 'Events Tab'. Hope  you like the site!</i></font></p>
  </div>