config/routes.rb
MFCPortal::Application.routes.draw do

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :activities
  resources :categories do
    resources :events
  end

  resources :events do
    resources :expenses
    collection do
      get "dashboard"
      get "welcome"
      get "gallery"
      get "contact_us"
      get "other_activity"
      get "event_activity_list"
    end
  end

  root :to => "events#dashboard"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name, :created_by, :updated_by

  validates :name, :description, :presence => true
  validates_length_of :name, :within => 6..30, :too_long => "Pick a shorter Name", :too_short => "Pick a longer name"
  has_many :events, :dependent => :destroy

  def self.create_new_category(category, new_category_name, new_category_description, current_user)

    if category.blank?
       if !new_category_name.nil?
           @category = Category.new(:name => new_category_name, :description => new_category_description, :created_by => current_user.id, :updated_by => current_user.id)
           @category.save
           category = @category.id
       else
         category
        end
    else
      category
     end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end

  def create
     @category = Category.new (params[:category])
     @category.created_by = current_user.id
     @category.updated_by = current_user.id

     if @category.save
       flash[:notice] = "Successfully created a new event category."
       redirect_to categories_path
     else
       flash[:notice] = @category.errors.full_messages.join(", ")
       render :action => :new
     end
  end


  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    if @category.destroy
      flash[:notice] = "Successfully deleted Category."
      redirect_to categories_url
    else
      flash[:notice] = "Category Could Not Be deleted."
      redirect_to categories_url
    end
  end


  def edit
      @category = Category.find(params[:id])
  end


  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    if @category.update_attributes(params[:category])
      flash[:notice] = "Successfully Updated Category."
      redirect_to categories_path
    else
      flash[:notice] = @category.errors.full_messages.join(", ")
      render :action => :edit
    end
  end
end

app/views/categories/_form.html.erb
<%= form_for (@category) do |f| %>
    <div><b><font size="3px">Type</font></b><br/>
     <%= f.text_field :name %></div><div id='em_category_name' class = "errors"> </div><br/>

    <div><b><font size="3px">Description</font></b><br/>
      <%= f.text_area :description, :rows => 5 %></div><div id='em_category_description' class = "errors"> </div><br/>

    <div style="height: 20px">
    </div>

  <div class="actions" id = "category_form_submit"><%= f.submit%>
    </div>

  <%end%>

app/views/categories/edit.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px">
  <h2> Edit Category </h2>
  <br/>
  <%=render 'form' %>

  <%= link_to 'Back', categories_path %>

</div>

app/views/categories/index.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px">
<%if @categories.blank? %>
<div>
</div>
<%else%>
<div style="overflow:auto;">
    <table border ="1px" id="activity_list_table" align = "center" >
      <thead>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><b>Category ID</b></td>
          <td style=" min-width: 20px "><b>Category Name</b></td>
          <td style=" padding-right: 5px; padding-left: 5px; max-width: 250px "><b>Description </b></td>
          <td style=" min-width: 20px "><b> Edit </b></td>
          <td style=" min-width: 20px "><b> Delete </b></td>
        </tr>
      </thead>

      <% @categories.each do |category|%>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><%= category.id%></td>
          <td style=" min-width: 20px "><%= category.name%></td>
          <td style=" padding-right: 5px; padding-left: 5px; max-width: 250px"><%= category.description%></td>
          <td style=" min-width: 20px "><%= link_to "Edit", edit_category_path(category)%></td>
          <td style=" min-width: 20px "><%= link_to (image_tag ("delete.png")), category, method: :delete, data: { confirm: 'Are you sure?' } %></td-->
        </tr>
      <%end%>
    </table>
  </div>
  <%end%>
  <div style ="margin-top :10px;  margin-left :90px">
  <%= link_to 'Create New Event Category ', new_category_path %> <br>
  <%= link_to 'Back', events_path %>
</div>
  </div>

app/views/categories/new.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px">
  <h2> Add New Event Category </h2>
  <br/>
  <%=render 'form' %>
  <div class="actions"> <%= link_to 'Cancel', categories_path %> </div>
</div>