config/routes.rb
MFCPortal::Application.routes.draw do

  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  resources :activities
  resources :categories do
    resources :events
  end

  resources :events do
    resources :expenses
    collection do
      get "dashboard"
      get "welcome"
      get "gallery"
      get "contact_us"
      get "other_activity"
      get "event_activity_list"
    end
  end

  root :to => "events#dashboard"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :title, :description, :created_by, :event_id
  #relationship with events
  belongs_to :event

  validates :description,:title, :presence => true
  validates_length_of :title, :within => 6..30, :too_long => "Pick a shorter Title", :too_short => "Pick a longer Title"

  # def self.create_new_activities(new_activity_title, new_activity_description, current_user)

  #   if !new_activity_title.nil?
  #     @activity = Activity.new(:title => new_activity_title, :description => new_activity_description, :created_by => current_user.id)
  #     @activity.save
  #     if activities.blank?
  #       activities = []
  #       activities << @activity.id
  #     else
  #       activities << @activity.id
  #     end
  #   else
  #     activities
  #   end
  # end


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

    #load_and_authorize_resource
    

    def index
        @activities = Activity.all
    end

    def new
        @activity = Activity.new
    end

    def create
       
        @activity = Activity.new (params[:activity])
        @activity.created_by = current_user.id
     
        if @activity.save
            flash[:notice] = "Successfully created a new activity."
            redirect_to activities_path
         else               
            flash[:notice] = @activity.errors.full_messages.join(", ")
            render :action => :new
        end
    end

    def destroy
        @activity = Activity.find(params[:id])    
        @activity.destroy
        if @activity.destroy
            flash[:notice] = "Successfully deleted activity."
            redirect_to activities_url
         else
            flash[:notice] = "activity Could Not Be deleted."
            redirect_to activities_url
        end
        
    end

    
    def edit
        @activity = Activity.find(params[:id]) 
     
    end


    def update
        @activity = Activity.find(params[:id]) 
        @activity.update_attributes(params[:activity]) 
        if @activity.update_attributes(params[:activity])
            flash[:notice] = "Successfully Updated activity."
            redirect_to activities_path
         else
            flash[:notice] = @activity.errors.full_messages.join(", ")
            render :action => :edit
        end
    end    

  



end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for (@activity) do |f| %>
	<table>
		<tr>
			<td>	
  				<div><b><font size="3px">Title</font></b><br/>
    			<%= f.text_field :title %></div>
    		</td>
    		<td>
    			<div id='em_activity_title' class = "errors"> </div>
    		</td>
    	</tr>

    	<tr>		
    		<td>
  				<div><b><font size="3px">Description</font></b><br/>
    			<%= f.text_area :description, :rows =>5 %></div>
    		</td>

    		<td>	
    			<div id='em_activity_description' class = "errors"> </div>
    		</td>	
    	</tr>
    	
    	<tr>
    		<td>	
  				<div style="height: 20px">
  				</div>
  			</td>	
  		</tr>
  		<tr>	
  			<td>
  				<div class="actions" id = "activity_form_submit"><%= f.submit%>
  				</div>
  			</td>	
  		</tr>	
	</table>
<%end%>

app/views/activities/edit.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px"> 
  <h2> Edit Activity </h2>

  <br/>
  <%=render 'form' %>

  <%= link_to 'Back', activities_path %>

</div>

app/views/activities/index.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px"> 
<%if @activities.blank? %>
<div>
</div>
<%else%>
<div style="overflow:auto;">
    <table border ="1px" id="activity_list_table" align = "center" >
      <thead>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px"><b>Activity ID</b></td>
          <td style=" min-width: 20px "><b>Title </b></td>
          <td style=" padding-right: 5px; padding-left: 5px; max-width: 250px "><b>Description </b></td>
          <td style=" min-width: 20px "><b> Edit </b></td>
          <td style=" min-width: 20px "><b> Delete </b></td>
        </tr>
      </thead>

      <%@activities.each do |activity|%>
        <tr>
          <td style=" padding-right: 5px; padding-left: 5px; min-width: 50px "><%= activity.id%></td>
          <td style=" min-width: 20px "><%= activity.title%></td>
          <td style=" padding-right: 5px; padding-left: 5px; max-width: 250px"><%= activity.description%></td>
          <td style=" min-width: 20px "><%= link_to "Edit", edit_activity_path(activity)%></td>
          <td style=" min-width: 20px "><%= link_to (image_tag ("delete.png")), activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%end%>
    </table>
  </div>
  <%end%>
  <div style ="margin-top :10px;  margin-left :90px">
  <%= link_to 'Create New Activity ', new_activity_path %> <br>
  <%= link_to 'Back', events_path %>
</div>
  </div>

app/views/activities/new.html.erb
<%= render 'shared/admin' %>
<div class= "well pull right span8" style = "min-height:500px; margin-left:50px"> 
  <h2> Add New Activity </h2>
  <br/>
  <%=render 'form' %>
  <div class="actions"> <%= link_to 'Cancel', activities_path %> </div>
</div>